I find this text ambiguous. Hope I got the intention right.
nais/naisdevice-approval pull request #8
Opened 2020-09-14 07:03 UTC by magnusesp

Improved text about Virtual Machine network connection.

2020-09-14 07:08 UTC, VegarM approved these changes

2020-09-14 07:12 UTC, jhrv approved these changes

2020-09-14 09:06 UTC, VegarM requested changes
Turns out it's the other way around. Bridge mode is desiered, not NAT.

2020-11-05 11:02 UTC, toby1knby submitted a review, later dismissed
No. This is the opposite of he intended message. Any VM running on your naisdevice should connect directly to the network, not by using "Shared IP with Host" functionality. For a docker container this is impractical of course but we are talking about a full blown VM.

2020-11-05 11:16 UTC, toby1knby requested changes
No. This is the opposite of he intended message. Any VM running on your naisdevice should connect directly to the network, not by using "Shared IP with Host" functionality. For a docker container this is impractical of course but we are talking about a full blown VM. Will add clarification if PR is not updated.

2020-11-05 11:21 UTC, closed without merging